<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container-fluid">
	  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </a>
	  <a class="brand" href="/">Project name</a>
	  <div class="btn-group pull-right">
		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		  <i class="icon-user"></i> Username
		  <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
		  <li><a href="#">Profile</a></li>
		  <li class="divider"></li>
		  <li><a href="logout.php">Sign Out</a></li>
		</ul>
	  </div>
	  <div class="nav-collapse">
		<ul class="nav">
		  <li class="active"><a href="#">Home</a></li>
		  <li><a href="#about">Ads</a></li>
		  <li><a href="post.php">Post</a></li>
		</ul>
	  </div><!--/.nav-collapse -->
	</div>
  </div>
</div>